{{- if .Values.persistentVolume.enabled | default false }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mongodb.fullname" . }}-pvc
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
    app: {{ include "mongodb.fullname" . }}
spec:
  storageClassName: {{ .Values.persistentVolume.storageClassName }}
  selector:
    matchLabels:
      app: {{ include "mongodb.fullname" . }}
  accessModes:
    {{- toYaml .Values.persistentVolume.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.size }}
{{- end }}
