replicaCount: 1

appEnv: ""

enableInitcontainer: true

image:
  repository: ghcr.io/scicatproject/backend-next
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  name: ""

podSecurityContext: {}

securityContext: {}

hostAliases: []

livenessProbe:
  httpGet:
    path: /explorer
    port: http
readinessProbe:
  httpGet:
    path: /explorer
    port: http

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "16m"
    nginx.org/client-max-body-size: "16m"
  hosts:
  - host: localhost
    paths:
    - path: /api
      pathType: ImplementationSpecific
    - path: /explorer
      pathType: ImplementationSpecific
  tls: []
configmap:
  EXPRESS_SESSION_SECRET: ""
  JWT_SECRET: ""
  JWT_EXPIRES_IN: 3600
  MONGODB_URI: ""
  PORT: 3000
  SITE: ""
  LOGBOOK_ENABLED: "no"
  ELASTICSEARCH_ENABLED: "no"
  ES_HOST: ""
  ES_USERNAME: ""
  MONGODB_COLLECTION: ""
  ES_MAX_RESULT: ""
  ES_FIELDS_LIMIT: ""
  ES_INDEX: ""
  ES_REFRESH: ""
  ACCESS_GROUPS_STATIC_VALUES: ""
  ACCESS_GROUPS_OIDCPAYLOAD_ENABLED: "false"
  ADMIN_GROUPS: ""
  CREATE_DATASET_GROUPS: ""
  CREATE_DATASET_WITH_PID_GROUPS: ""
  DELETE_GROUPS: ""
  DATASET_CREATION_VALIDATION_ENABLED: "false"
  DATASET_CREATION_VALIDATION_REGEX: ""
  PROPOSAL_GROUPS: ""
  SAMPLE_GROUPS: ""
  OIDC_ISSUER: ""
  OIDC_AUTHORIZATION_URL: ""
  OIDC_CLIENT_ID: ""
  OIDC_CLIENT_SECRET: ""
  OIDC_CALLBACK_URL: ""
  OIDC_SCOPE: 'openid profile email'
  OIDC_SUCCESS_URL: ""
env:
- name: ES_PASSWORD
  valueFrom:
    secretKeyRef:
      name: scicat-app-elastic-search-secret
      key: ELASTIC_PASSWORD

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
