backend:
  appEnv: development
  enableInitcontainer: true
  image:
    repository: ghcr.io/scicatproject/backend-next
    tag: v4.5.1
    pullPolicy: Always
  ingress:
    enabled: true
    hosts:
    - host: localhost
      paths:
      - path: /api
        pathType: ImplementationSpecific
      - path: /explorer
        pathType: ImplementationSpecific
  configmap:
    EXPRESS_SESSION_SECRET: "secret"
    JWT_SECRET: random
    JWT_EXPIRES_IN: "3600"
    MONGODB_URI: "mongodb://scicat-app-mongodb/scicat-db"
    PORT: "3000"
    SITE: LOCAL
    LOGBOOK_ENABLED: "no"
    ELASTICSEARCH_ENABLED: "yes"
    ES_HOST: http://scicat-app-elastic-search:9200
    ES_USERNAME: elastic
    MONGODB_COLLECTION: Dataset
    ES_MAX_RESULT: "210000"
    ES_FIELDS_LIMIT: "400000"
    ES_INDEX: "dataset"
    ES_REFRESH: "wait_for"
    ACCESS_GROUPS_STATIC_VALUES: ""
    ACCESS_GROUPS_OIDCPAYLOAD_ENABLED: false
    ADMIN_GROUPS: "admin, ingestor"
    CREATE_DATASET_GROUPS: ""
    CREATE_DATASET_WITH_PID_GROUPS: ""
    DELETE_GROUPS: "archivemanager"
    DATASET_CREATION_VALIDATION_ENABLED: "false"
    DATASET_CREATION_VALIDATION_REGEX: ""
    PROPOSAL_GROUPS: "proposalingestor"
    SAMPLE_GROUPS: ""
    OIDC_ISSUER: ""
    OIDC_AUTHORIZATION_URL: ""
    OIDC_CLIENT_ID: ""
    OIDC_CLIENT_SECRET: ""
    OIDC_CALLBACK_URL: ""
    OIDC_SCOPE: 'openid profile email'
    OIDC_SUCCESS_URL: ""
  env:
  - name: ES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: scicat-app-elastic-search-secret
        key: ELASTIC_PASSWORD

frontend:
  appEnv: development
  image:
    repository: ghcr.io/scicatproject/frontend
    tag: v.4.4.2
    pullPolicy: Always
  ingress:
    enabled: true
    hosts:
    - host: localhost
      paths:
      - path: /
        pathType: ImplementationSpecific

mongodb:
  appEnv: development
  autoscaling:
    enabled: false
  secret:
    MONGODB_URI: ""
  persistentVolume:
    enabled: false
    storageClassName: ""

elastic-search:
  appEnv: development
  image:
    repository: docker.elastic.co/elasticsearch/elasticsearch
    tag: 8.8.2
    pullPolicy: Always
  configmap:
    node.name: "es01"
    cluster.name: "es-cluster"
    bootstrap.memory_lock: "true"
    discovery.type: "single-node"
    xpack.security.enabled: 'true'
    xpack.security.http.ssl.enabled: 'false'
    ES_JAVA_OPTS: "-Xms2g -Xmx2g"
  secret:
    ELASTIC_PASSWORD: ZmFrZVBhc3N3b3Jk
  persistentVolume:
    enabled: false
    storageClassName: nfs-storage
    size: 10Gi
    accessModes:
    - ReadWriteMany
  requests:
    cpu: '100m'
    memory: '4Gi'
  limits:
    cpu: '1000m'
    memory: 4Gi
  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 3
    timeoutSeconds: 5
