apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scicat-mongodb.fullname" . }}-secret
  labels:
    {{- include "scicat-mongodb.labels" . | nindent 4 }}
type: Opaque
data:
  {{- toYaml .Values.secret | nindent 2 }}
