apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}-configmap
  labels:
{{ include "frontend.labels" . | indent 4 }}
data:
  theme.json: |-
{{ .Files.Get "envfiles/theme.json" | indent 4 }}
  config.json: |-
{{ .Files.Get "envfiles/config.json" | indent 4 }}
binaryData:
  favicon.ico: |-
{{ .Files.Get "envfiles/favicon.ico" | b64enc | indent 4 }}
  site-login-background.png: |-
{{ .Files.Get "envfiles/site.png" | b64enc | indent 4 }}
  site-login-logo.png: |-
{{ .Files.Get "envfiles/site-logo.png" | b64enc | indent 4 }}
  esslogo-white.png: |-
{{ .Files.Get "envfiles/esslogo-white.png" | b64enc | indent 4 }}

