apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scicat-frontend.fullname" . }}
  labels:
{{ include "scicat-frontend.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "scicat-frontend.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "scicat-frontend.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "scicat-frontend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/assets/config.json
              subPath: config.json
            - name: config-volume
              mountPath: /usr/share/nginx/html/assets/theme.json
              subPath: theme.json
            - name: config-volume
              mountPath: /usr/share/nginx/html/assets/images/site-login-background.png
              subPath: site-login-background.png
            - name: config-volume
              mountPath: /usr/share/nginx/html/assets/images/site-login-logo.png
              subPath: site-login-logo.png
            - name: config-volume
              mountPath: /usr/share/nginx/html/assets/images/site-header-logo.png
              subPath: esslogo-white.png
            - name: config-volume
              mountPath: /usr/share/nginx/html/favicon.ico
              subPath: favicon.ico
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "scicat-frontend.fullname" . }}-configmap
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
