apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scicat-backend.fullname" . }}-configmap
  labels:  {{ include "scicat-backend.labels" . | nindent 4 }}
data:
  .env: |-
{{ .Files.Get "envfiles/.env.dev" | indent 4 }}
  functionalAccounts.json: |-
{{ .Files.Get "envfiles/functionalAccounts.dev.json" | indent 4 }}
  loggers.json: |-
{{ .Files.Get "envfiles/loggers.dev.json" | indent 4 }}
  frontend.config.json: |-
{{ .Files.Get "envfiles/frontend.config.dev.json" | indent 4 }}
  frontend.theme.json: |-
{{ .Files.Get "envfiles/frontend.theme.dev.json" | indent 4 }}

