apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-configmap
  labels:  {{ include "backend.labels" . | nindent 4 }}
data:
  {{- with .Values.configmap }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  functionalAccounts.json: |-
{{ .Files.Get "envfiles/functionalAccounts.json" | indent 4 }}
  loggers.json: |-
{{ .Files.Get "envfiles/loggers.json" | indent 4 }}
  frontend.config.json: |-
{{ .Files.Get "envfiles/frontend.config.json" | indent 4 }}
  frontend.theme.json: |-
{{ .Files.Get "envfiles/frontend.theme.json" | indent 4 }}
